name: Build Android App

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Unzip Project Files
      run: |
        unzip noise.zip
        chmod +x gradlew

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install NDK and CMake via SDKManager
      run: |
        echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "ndk;27.3.13750724" "cmake;3.22.1"

    - name: Clean Local Properties
      run: |
        # पुरानी गंदी local.properties फाइल को उड़ा देते हैं ताकि gradle खुद सही पाथ ले ले
        rm -f local.properties

    - name: Build Debug APK
      run: ./gradlew assembleDebug --no-daemon
