name: Build Android App

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Unzip Project Files
      run: |
        unzip noise.zip
        chmod +x gradlew

    - name: Clean Old CXX and Build Caches
      run: |
        # पुराने कैश्ड पाथ और जंक फाइल्स को जड़ से साफ़ करते हैं ताकि CMake नया पाथ ले सके
        rm -rf app/.cxx app/build build .gradle
        rm -f local.properties

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install NDK and CMake via SDKManager
      run: |
        echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "ndk;27.3.13750724" "cmake;3.22.1"

    - name: Build Debug APK
      run: ./gradlew assembleDebug --no-daemon
