name: Build Android App

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Unzip Project Files
      run: |
        unzip noise.zip
        chmod +x gradlew

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Android SDK & NDK
      uses: android-actions/setup-android@v3
      with:
        ndk-version: '27.3.13750724'

    - name: Clean Local Properties
      run: |
        rm -f local.properties
        find . -name "local.properties" -exec rm -f {} \;

    - name: Build Debug APK
      run: ./gradlew assembleDebug --no-daemon
